# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Devent' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Devent
  pod 'RNMobileCenter', '~> 0.1.0'
  pod 'MobileCenter', '~> 0.3.0'

  

end
